# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #F5F0FF;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #E8DCFF;\n"
"    border-radius: 12px;\n"
"    margin-top: 12px;\n"
"    padding-top: 8px;\n"
"    font-weight: 600;\n"
"    font-size: 13px;\n"
"    color: #6B4BA0;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 15px;\n"
"    padding: 2px 8px;\n"
"    background-color: #DFD3F5;\n"
"    border-radius: 6px;\n"
"    color: #5A3D8A;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #D4C5F9;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: 600;\n"
"    color: #5A3D8A;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C4B0F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B49FE8;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #E8E8E8;\n"
"    color: #A0A0A0;\n"
"}\n"
"\n"
"QPushButton#startButton {\n"
"    background-color: #B8E6D5;\n"
"    color: #2D6A4F;\n"
"}\n"
"\n"
"QPushButton#startButton:hover {\n"
"    background-color: #A0DCCA;\n"
"}\n"
"\n"
"QPushButton#pauseResumeButton {\n"
"    background-color: #FFE5B4;\n"
"    color: #8B6914;\n"
"}\n"
"\n"
"QPushButton#pauseResumeButton:hover {\n"
"    background-color: #FFD89B;\n"
"}\n"
"\n"
"QPushButton#stopButton {\n"
"    background-color: #FFB8C6;\n"
"    color: #8B2E3D;\n"
"}\n"
"\n"
"QPushButton#stopButton:hover {\n"
"    background-color: #FFA0B3;\n"
"}\n"
"\n"
"QPushButton#loadPreviousButton {\n"
"    background-color: #C8E0F9;\n"
"    color: #2E5A8B;\n"
"}\n"
"\n"
"QPushButton#loadPreviousButton:hover {\n"
"    background-color: #B0D4F5;\n"
"}\n"
"\n"
"QPushButton#sortButton {\n"
"    background-color: #FFD4E5;\n"
"    color: #8B2E5A;\n"
"}\n"
"\n"
"QPushButton#sortButton:hover {\n"
"    background-color: #FFBDD8;\n"
"}\n"
"\n"
"QPushButton#addFilterButton {\n"
"    background-color: #D4F9E6;\n"
"    color: #2D6A4F;\n"
"}\n"
"\n"
"QPushButton#addFilterButton:hover {\n"
"    background-color: #BCEFD9;\n"
"}\n"
"\n"
"QPushButton#applyFilterButton {\n"
"    background-color: #D4F9E6;\n"
"    color: #2D6A4F;\n"
"}\n"
"\n"
"QPushButton#applyFilterButton:hover {\n"
"    background-color: #BCEFD9;\n"
"}\n"
"\n"
"QPushButton#clearFilterButton {\n"
"    background-color: #FFE0CC;\n"
"    color: #8B4513;\n"
"}\n"
"\n"
"QPushButton#clearFilterButton:hover {\n"
"    background-color: #FFD0B3;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 2px solid #E8DCFF;\n"
"    border-radius: 8px;\n"
"    background-color: #F9F5FF;\n"
"    text-align: center;\n"
"    font-weight: 600;\n"
"    color: #6B4BA0;\n"
"    height: 24px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #D4C5F9, stop:1 #B8A8E8);\n"
"    border-radius: 6px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #5A3D8A;\n"
"    font-weight: 500;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel#sortTimeLabel {\n"
"    background-color: #FFF9E6;\n"
"    border: 2px solid #FFE5B4;\n"
"    border-radius: 6px;\n"
"    padding: 4px 8px;\n"
"    color: #8B6914;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #E8DCFF;\n"
"    border-radius: 6px;\n"
"    padding: 6px 10px;\n"
"    color: #5A3D8A;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #D4C5F9;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 6px solid #8B6FB8;\n"
"    width: 0;\n"
"    height: 0;\n"
"    margin-right: 8px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #E8DCFF;\n"
"    border-radius: 6px;\n"
"    padding: 6px 10px;\n"
"    color: #5A3D8A;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #C4B0F0;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: #5A3D8A;\n"
"    font-weight: 500;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #D4C5F9;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #B8A8E8;\n"
"    border: 2px solid #8B6FB8;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #B8A8E8;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #E8DCFF;\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"    color: #5A3D8A;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #DFD3F5;\n"
"    color: #5A3D8A;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #F0E8FF;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F9F5FF;\n"
"    border: 2px solid #E8DCFF;\n"
"    border-radius: 8px;\n"
"    gridline-color: #F0E8FF;\n"
"    color: #5A3D8A;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #DFD3F5;\n"
"    color: #5A3D8A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #DFD3F5;\n"
"    color: #5A3D8A;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-right: 1px solid #CFBFF0;\n"
"    border-bottom: 2px solid #CFBFF0;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: #F9F5FF;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #D4C5F9;\n"
"    border-radius: 6px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #C4B0F0;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: #F9F5FF;\n"
"    height: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #D4C5F9;\n"
"    border-radius: 6px;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #C4B0F0;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.controlGroup.setMaximumSize(QtCore.QSize(16777215, 130))
        self.controlGroup.setObjectName("controlGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.controlGroup)
        self.verticalLayout_4.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.controlGroup)
        self.startButton.setMinimumSize(QtCore.QSize(110, 40))
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.pauseResumeButton = QtWidgets.QPushButton(self.controlGroup)
        self.pauseResumeButton.setEnabled(False)
        self.pauseResumeButton.setMinimumSize(QtCore.QSize(110, 40))
        self.pauseResumeButton.setObjectName("pauseResumeButton")
        self.horizontalLayout.addWidget(self.pauseResumeButton)
        self.stopButton = QtWidgets.QPushButton(self.controlGroup)
        self.stopButton.setEnabled(False)
        self.stopButton.setMinimumSize(QtCore.QSize(110, 40))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progressLabel = QtWidgets.QLabel(self.controlGroup)
        self.progressLabel.setObjectName("progressLabel")
        self.horizontalLayout_5.addWidget(self.progressLabel)
        self.progressBar = QtWidgets.QProgressBar(self.controlGroup)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setMaximum(150)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.controlGroup)
        self.sortGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.sortGroup.setMaximumSize(QtCore.QSize(16777215, 110))
        self.sortGroup.setObjectName("sortGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sortGroup)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sortColumnLabel = QtWidgets.QLabel(self.sortGroup)
        self.sortColumnLabel.setObjectName("sortColumnLabel")
        self.horizontalLayout_2.addWidget(self.sortColumnLabel)
        self.sortColumnsList = QtWidgets.QListWidget(self.sortGroup)
        self.sortColumnsList.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sortColumnsList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.sortColumnsList.setFlow(QtWidgets.QListView.LeftToRight)
        self.sortColumnsList.setObjectName("sortColumnsList")
        item = QtWidgets.QListWidgetItem()
        self.sortColumnsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sortColumnsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sortColumnsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sortColumnsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sortColumnsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sortColumnsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sortColumnsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sortColumnsList.addItem(item)
        self.horizontalLayout_2.addWidget(self.sortColumnsList)
        self.sortAlgoLabel = QtWidgets.QLabel(self.sortGroup)
        self.sortAlgoLabel.setObjectName("sortAlgoLabel")
        self.horizontalLayout_2.addWidget(self.sortAlgoLabel)
        self.sortAlgoCombo = QtWidgets.QComboBox(self.sortGroup)
        self.sortAlgoCombo.setMinimumSize(QtCore.QSize(120, 32))
        self.sortAlgoCombo.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sortAlgoCombo.setObjectName("sortAlgoCombo")
        self.sortAlgoCombo.addItem("")
        self.sortAlgoCombo.addItem("")
        self.sortAlgoCombo.addItem("")
        self.sortAlgoCombo.addItem("")
        self.sortAlgoCombo.addItem("")
        self.horizontalLayout_2.addWidget(self.sortAlgoCombo)
        self.sortButton = QtWidgets.QPushButton(self.sortGroup)
        self.sortButton.setMinimumSize(QtCore.QSize(100, 32))
        self.sortButton.setObjectName("sortButton")
        self.horizontalLayout_2.addWidget(self.sortButton)
        self.sortTimeLabel = QtWidgets.QLabel(self.sortGroup)
        self.sortTimeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.sortTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sortTimeLabel.setObjectName("sortTimeLabel")
        self.horizontalLayout_2.addWidget(self.sortTimeLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.sortGroup)
        self.searchGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.searchGroup.setMaximumSize(QtCore.QSize(16777215, 130))
        self.searchGroup.setObjectName("searchGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.searchGroup)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.searchColumnLabel = QtWidgets.QLabel(self.searchGroup)
        self.searchColumnLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.searchColumnLabel.setObjectName("searchColumnLabel")
        self.gridLayout.addWidget(self.searchColumnLabel, 0, 0, 1, 1)
        self.searchColumnCombo = QtWidgets.QComboBox(self.searchGroup)
        self.searchColumnCombo.setMinimumSize(QtCore.QSize(120, 32))
        self.searchColumnCombo.setObjectName("searchColumnCombo")
        self.searchColumnCombo.addItem("")
        self.searchColumnCombo.addItem("")
        self.searchColumnCombo.addItem("")
        self.searchColumnCombo.addItem("")
        self.searchColumnCombo.addItem("")
        self.searchColumnCombo.addItem("")
        self.searchColumnCombo.addItem("")
        self.searchColumnCombo.addItem("")
        self.gridLayout.addWidget(self.searchColumnCombo, 0, 1, 1, 1)
        self.operatorLabel = QtWidgets.QLabel(self.searchGroup)
        self.operatorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.operatorLabel.setObjectName("operatorLabel")
        self.gridLayout.addWidget(self.operatorLabel, 0, 2, 1, 1)
        self.operatorCombo = QtWidgets.QComboBox(self.searchGroup)
        self.operatorCombo.setMinimumSize(QtCore.QSize(130, 32))
        self.operatorCombo.setObjectName("operatorCombo")
        self.operatorCombo.addItem("")
        self.operatorCombo.addItem("")
        self.operatorCombo.addItem("")
        self.operatorCombo.addItem("")
        self.operatorCombo.addItem("")
        self.operatorCombo.addItem("")
        self.operatorCombo.addItem("")
        self.gridLayout.addWidget(self.operatorCombo, 0, 3, 1, 1)
        self.searchValueLabel = QtWidgets.QLabel(self.searchGroup)
        self.searchValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.searchValueLabel.setObjectName("searchValueLabel")
        self.gridLayout.addWidget(self.searchValueLabel, 0, 4, 1, 1)
        self.searchValueInput = QtWidgets.QLineEdit(self.searchGroup)
        self.searchValueInput.setMinimumSize(QtCore.QSize(160, 32))
        self.searchValueInput.setObjectName("searchValueInput")
        self.gridLayout.addWidget(self.searchValueInput, 0, 5, 1, 1)
        self.addFilterButton = QtWidgets.QPushButton(self.searchGroup)
        self.addFilterButton.setMinimumSize(QtCore.QSize(110, 32))
        self.addFilterButton.setObjectName("addFilterButton")
        self.gridLayout.addWidget(self.addFilterButton, 0, 6, 1, 1)
        self.compositeLabel = QtWidgets.QLabel(self.searchGroup)
        self.compositeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.compositeLabel.setObjectName("compositeLabel")
        self.gridLayout.addWidget(self.compositeLabel, 1, 0, 1, 1)
        self.radioLayout = QtWidgets.QHBoxLayout()
        self.radioLayout.setSpacing(15)
        self.radioLayout.setObjectName("radioLayout")
        self.andRadio = QtWidgets.QRadioButton(self.searchGroup)
        self.andRadio.setChecked(True)
        self.andRadio.setObjectName("andRadio")
        self.radioLayout.addWidget(self.andRadio)
        self.orRadio = QtWidgets.QRadioButton(self.searchGroup)
        self.orRadio.setObjectName("orRadio")
        self.radioLayout.addWidget(self.orRadio)
        self.notRadio = QtWidgets.QRadioButton(self.searchGroup)
        self.notRadio.setObjectName("notRadio")
        self.radioLayout.addWidget(self.notRadio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.radioLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.radioLayout, 1, 1, 1, 3)
        self.applyFilterButton = QtWidgets.QPushButton(self.searchGroup)
        self.applyFilterButton.setMinimumSize(QtCore.QSize(110, 32))
        self.applyFilterButton.setObjectName("applyFilterButton")
        self.gridLayout.addWidget(self.applyFilterButton, 1, 5, 1, 1)
        self.clearFilterButton = QtWidgets.QPushButton(self.searchGroup)
        self.clearFilterButton.setMinimumSize(QtCore.QSize(110, 32))
        self.clearFilterButton.setObjectName("clearFilterButton")
        self.gridLayout.addWidget(self.clearFilterButton, 1, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.searchGroup)
        self.dataGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.dataGroup.setObjectName("dataGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dataGroup)
        self.verticalLayout_3.setContentsMargins(10, 15, 10, 10)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dataTable = QtWidgets.QTableWidget(self.dataGroup)
        self.dataTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dataTable.setAlternatingRowColors(True)
        self.dataTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.dataTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(8)
        self.dataTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(7, item)
        self.dataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.dataTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.dataTable)
        self.verticalLayout.addWidget(self.dataGroup)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setStyleSheet("\n"
"QMenuBar {\n"
"    background-color: #DFD3F5;\n"
"    color: #5A3D8A;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #C4B0F0;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #E8DCFF;\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 6px 24px;\n"
"    border-radius: 4px;\n"
"    color: #5A3D8A;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #DFD3F5;\n"
"}\n"
"    ")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("\n"
"QStatusBar {\n"
"    background-color: #DFD3F5;\n"
"    color: #5A3D8A;\n"
"    font-weight: 500;\n"
"}\n"
"    ")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Web Scraper Control Panel"))
        self.controlGroup.setTitle(_translate("MainWindow", "🚀 Scraping Controls"))
        self.startButton.setText(_translate("MainWindow", "▶ Start"))
        self.pauseResumeButton.setText(_translate("MainWindow", "⏸ Pause"))
        self.stopButton.setText(_translate("MainWindow", "⏹ Stop"))
        self.progressLabel.setText(_translate("MainWindow", "📊 Progress:"))
        self.progressBar.setFormat(_translate("MainWindow", "%v / 150 pages"))
        self.sortGroup.setTitle(_translate("MainWindow", "🔄 Sorting Options"))
        self.sortColumnLabel.setText(_translate("MainWindow", "📋 Columns:"))
        __sortingEnabled = self.sortColumnsList.isSortingEnabled()
        self.sortColumnsList.setSortingEnabled(False)
        item = self.sortColumnsList.item(0)
        item.setText(_translate("MainWindow", "Column 1"))
        item = self.sortColumnsList.item(1)
        item.setText(_translate("MainWindow", "Column 2"))
        item = self.sortColumnsList.item(2)
        item.setText(_translate("MainWindow", "Column 3"))
        item = self.sortColumnsList.item(3)
        item.setText(_translate("MainWindow", "Column 4"))
        item = self.sortColumnsList.item(4)
        item.setText(_translate("MainWindow", "Column 5"))
        item = self.sortColumnsList.item(5)
        item.setText(_translate("MainWindow", "Column 6"))
        item = self.sortColumnsList.item(6)
        item.setText(_translate("MainWindow", "Column 7"))
        item = self.sortColumnsList.item(7)
        item.setText(_translate("MainWindow", "Column 8"))
        self.sortColumnsList.setSortingEnabled(__sortingEnabled)
        self.sortAlgoLabel.setText(_translate("MainWindow", "⚡ Algorithm:"))
        self.sortAlgoCombo.setItemText(0, _translate("MainWindow", "Quick Sort"))
        self.sortAlgoCombo.setItemText(1, _translate("MainWindow", "Merge Sort"))
        self.sortAlgoCombo.setItemText(2, _translate("MainWindow", "Bubble Sort"))
        self.sortAlgoCombo.setItemText(3, _translate("MainWindow", "Heap Sort"))
        self.sortAlgoCombo.setItemText(4, _translate("MainWindow", "Insertion Sort"))
        self.sortButton.setText(_translate("MainWindow", "✨ Apply Sort"))
        self.sortTimeLabel.setText(_translate("MainWindow", "⏱ Time: 0 ms"))
        self.searchGroup.setTitle(_translate("MainWindow", "🔍 Search and Filter"))
        self.searchColumnLabel.setText(_translate("MainWindow", "Column:"))
        self.searchColumnCombo.setItemText(0, _translate("MainWindow", "Column 1"))
        self.searchColumnCombo.setItemText(1, _translate("MainWindow", "Column 2"))
        self.searchColumnCombo.setItemText(2, _translate("MainWindow", "Column 3"))
        self.searchColumnCombo.setItemText(3, _translate("MainWindow", "Column 4"))
        self.searchColumnCombo.setItemText(4, _translate("MainWindow", "Column 5"))
        self.searchColumnCombo.setItemText(5, _translate("MainWindow", "Column 6"))
        self.searchColumnCombo.setItemText(6, _translate("MainWindow", "Column 7"))
        self.searchColumnCombo.setItemText(7, _translate("MainWindow", "Column 8"))
        self.operatorLabel.setText(_translate("MainWindow", "Operator:"))
        self.operatorCombo.setItemText(0, _translate("MainWindow", "Equals"))
        self.operatorCombo.setItemText(1, _translate("MainWindow", "Contains"))
        self.operatorCombo.setItemText(2, _translate("MainWindow", "Starts With"))
        self.operatorCombo.setItemText(3, _translate("MainWindow", "Ends With"))
        self.operatorCombo.setItemText(4, _translate("MainWindow", "Not Equals"))
        self.operatorCombo.setItemText(5, _translate("MainWindow", "Greater Than"))
        self.operatorCombo.setItemText(6, _translate("MainWindow", "Less Than"))
        self.searchValueLabel.setText(_translate("MainWindow", "Value:"))
        self.searchValueInput.setPlaceholderText(_translate("MainWindow", "Enter value..."))
        self.addFilterButton.setText(_translate("MainWindow", "➕ Add Filter"))
        self.compositeLabel.setText(_translate("MainWindow", "Logic:"))
        self.andRadio.setText(_translate("MainWindow", "AND"))
        self.orRadio.setText(_translate("MainWindow", "OR"))
        self.notRadio.setText(_translate("MainWindow", "NOT"))
        self.applyFilterButton.setText(_translate("MainWindow", "✓ Apply Filters"))
        self.clearFilterButton.setText(_translate("MainWindow", "✕ Clear Filters"))
        self.dataGroup.setTitle(_translate("MainWindow", "📊 Scraped Data"))
        self.dataTable.setSortingEnabled(False)
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Column 1"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Column 2"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Column 3"))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Column 4"))
        item = self.dataTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Column 5"))
        item = self.dataTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Column 6"))
        item = self.dataTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Column 7"))
        item = self.dataTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Column 8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
